name: build & deploy lambda docker image to ECR

on: [push]

jobs:
  deploy-lambda-docker-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker-lambda
        IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    - name: Wait for image to be available in ECR
      run: |
        while true; do
          if aws ecr describe-images --repository-name docker-lambda --image-ids imageTag=$IMAGE_TAG --output text | grep -q "imageManifest"; then
            break
          else
            echo "Waiting for image to be available in ECR..."
            sleep 10
          fi
        done
    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name docker-lambda-function --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
